// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreWebApi.zAppContexts;

#nullable disable

namespace StoreWebApi.Migrations.WalletMigrations
{
    [DbContext(typeof(WalletAppDbContext))]
    [Migration("20260513133348_addWalletCurrency")]
    partial class addWalletCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreWebApi.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wallets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 5000,
                            Currency = "USD $",
                            UserEmail = "saad@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 4000,
                            Currency = "USD $",
                            UserEmail = "ahmed@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
